### ISSUE TITLE
Calculating the impact angle of a hit_list ray

### ISSUE THREAD

**Issue by frizensami** [cihologramas/pyoptools#103]
Hello, and thank you very much for making this software!

I'm trying to compute the impact angle for each ray that hits a CCD sensor. If the ccd sensor is represented by `CCD`, I am trying to achieve this with:

```
for impactPoints, ray in CCD.hit_list:
   impactRayDirection = ray.dir
```

Does `impactRayDirection` represent the impact angle?

Thank you!

**Comment by ramezquitao** [comment]
Hello. The ray direction is a unitary vector that represents the
"direction" of propagation of the ray. This is, a ray propagating in the Z
direction will have a dir of (0,0,1). To get the angle incidence angle, you
will have to compare this with the normal vector of the surface. I guess
using something like a dot product could be used for this.

**Comment by frizensami** [comment]
Thank you very much! I managed to transform the system 3D plots that looked like this:
![image](https://user-images.githubusercontent.com/5507069/126505849-e36a68c3-9d95-441f-b17e-2ff9c16d29bb.png)

into plots describing whether a ray hit the CCD sensor from the left or right side of lens' axis here:

![image](https://user-images.githubusercontent.com/5507069/126505980-9397f450-73c2-47e1-9180-7aa01d366f93.png)
