### ISSUE TITLE
Cleanup spaces ?

### ISSUE THREAD

**Issue by ederag** [cihologramas/pyoptools#111]
Spaces changes make PR difficult to review (e.g. #106),
(or to create, for those who take care to avoid space changes).
One way would be to add a [`.editorconfig`](https://editorconfig.org/) file with the expected format.

On the same line, a code formatter such as [black](https://black.readthedocs.io/en/stable/) might help a lot.
https://deepsource.io/blog/python-code-formatters/

If you wish, I'd be glad to give more details about the procedure (very easy) and help with the review
(or file PRs if you prefer).

**Comment by ramezquitao** [comment]
@ederag I just merged a repo where black was run to the python files, and some of the cython files were fixed using autopep8 with some relevant options. I just tested the merge with some of my complex projects, and everything seems to be running OK. Regarding the .editorconfig please add it if you can, or point me to the info to generate it.
