### ISSUE TITLE
vedo library for viz

### ISSUE THREAD

**Issue by marcomusy** [cihologramas/pyoptools#117]
Just encountered your cool library, and would like to point you to [`vedo`](https://github.com/marcomusy/vedo/blob/master/examples/simulations/optics_main2.py) (i'm the main developer btw), maybe it's helpful for visualization

![Screenshot from 2022-03-21 12-47-31](https://user-images.githubusercontent.com/32848391/159255593-9abc54b9-dbb4-4243-983e-6c9d00b89e3b.png)

https://vedo.embl.es/#gallery

Regards
Marco

**Comment by ederag** [comment]
Thanks, that's interesting !
@ramezquitao already invested a lot of work into other backends, so it might be overwhelming to add another one though.

Nevertheless, I tried `vedo` under jupyter:
```bash
# In a separate virtual environment; I use `venvwrapper -c vedo`
pip install vedo
pip install --upgrade pip
pip install wheel
pip install Pygments

vedo -r optics_main2
works, a window opens with the the 3D plot, fine.

pip install jupyter
pip install k3d

jupyter nbextension install --py --sys-prefix k3d
jupyter nbextension enable k3d --py --sys-prefix

# otherwise it does not find the optics_base.py that sits there
cd ~/.venv/vedo/lib64/python3.6/site-packages/vedo/examples/simulations

jupyter notebook
```
Then copy/paste blocks from `optics_main2.py` blocks into the notebook.
It works, but the plot happens in a separate window.
This window can't be closed, unless the notebook is closed.

How to get the plot integrated into jupyter ?

**Comment by ramezquitao** [comment]
As mentioned in other issue, the current interactive plots in pyoptools are too slow in jupyter (and limited). It would be very interesting to use this library if we could use it to make a good 3D interactive backend for Jupyter, that hopefully could run in collab. This could be a big boost for pyoptools.

**Comment by marcomusy** [comment]
> (I'd like a "run all" with several plots to generate all images, without the need for any interaction).

well... then it's easier, have you tried `backed='2d'`
and 
`settings.screeshotScale=-1`
will yield a smaller image.

**Comment by marcomusy** [comment]
PS2:
.. if you have transparent objects this also might help:
`settings.useDepthPeeling = True`

**Comment by ederag** [comment]
By "without the need for interaction", I meant that the "run all" should behave as a batch run,
but subsequent interaction would be welcome sometimes,
so while the '2d' backend works fine, it won't be enough to switch to vedo.

`settings.useDepthPeeling = True` did not help, the `k3d` image is the same.
I will not have time to try again in a while.

**Comment by marcomusy** [comment]
In that case I think you don't need any vtk-based solution, if you look for a different jupyter backend you probably want to go straight to `k3d` and skip vtk altogether.

**Comment by ederag** [comment]
@marcomusy I'm just one user here (@ramezquitao is the maintainer), and there is value in the default `vedo` vtk backend.
Besides, there are many different use cases, so thanks for chiming in !
