### ISSUE TITLE
Python +3.4

### ISSUE THREAD

**Issue by fariza** [cihologramas/pyoptools#13]
Hola

Que han pensado de hacer el codigo compatible con python >=3.4?

Es mucho codigo y bastante complejo :+1:
Antes de proponer cualquier cosa tengo un par de preguntas
- Ustedes que tan PEP8 fans son?
- Hay muchos `from xxx.yy import *` ustedes quieren manter este comportamiento?
- Que tan casados estan con wx?

**Comment by ramezquitao** [comment]
Hola

   - Nosotros aun no hemos hecho el cambio a python 3 en ninguno de
   nuestros proyectos. Estamos en mora de hacerlo, y pues si, realmente todo
   el código hoy debería correr en python 3.4
   - Pues la verdad es que seria bueno tratar de que el código cumpla con
   el PEP8. El pyoptools es código viejo y se escribió sin tener esas
   recomendaciones en cuenta. Para facilitar el mantenimiento del código sería
   bueno corregir.
   - Ver punto anterior...
   - Hay un visor que usa wx (y opengl), pero la verdad es que creemos que
   sería mejor poder hacer todo en notebooks de ipython. Para esto hemos
   pensado en crear algunos widgets del notebook, que faciliten el trabajo, y
   permitan realizar algunas tareas de manera mas similar a como se harían en
   zeemax y oslo. El único problema que se tiene en este momento con
   implementar todo dentro un notebook de ipython, es que para poder hacer los
   renderings se está usando la librería osmesa (offscreen mesa), la cual
   permite hacer los renderings offscreen para luego mostrarlos como un png en
   el notebook. A mi me gustaría cambiar eso y comenzar a usar webgl, esto
   permitiría que se use la GPU del computador en el que se está corriendo el
   notebook y tener unos resultados mas interactivos. No se que piensa usted
   al respecto.

Respecto a como funciona el código, ya hay muchas cosas de las que yo no me
acuerdo, pero si quiere podemos hacer un skype o un hagouts, y yo le cuento
por encima de lo poco que me acuerdo. De pronto usted tiene mejores ideas
para optimizarlo.






Ricardo Amézquita Orozco

ramezquitao@cihologramas.com
ramezquitao@unal.edu.co
ramezquitao@gmail.com

**Comment by fariza** [comment]
Con lo de los widgets de IPython no estoy tan seguro. 
Yo como veo la cosa debería ser separada en 2. 
* Por un lado la librería que permite ser integrada (embedded) en otras cosas.
* El uso más general de la librería. Una y app/widgets/api/gui al estilo zemax puede ser en ipython

**Comment by ramezquitao** [comment]
Si, la idea es esa. Que la librería pueda ser integrada en otras cosas, pero que por facilidad traiga una pequeña aplicación que permita usarla mas fácil. Por ahora yo pensaba hacer eso en un modulo aparte, y luego si se crece, separarlo a un repositorio diferente

**Comment by fariza** [comment]
Me parece perfecto en un modulo aparte.
Revisando el webgl aparentemente esta bien soportado por el webkit, asi que en principio se puede usar casi que con cualquier GUI framework.

**Comment by fariza** [comment]
ya hay tests que fallan en python3.4, el objetivo debe ser que todos pasen,

**Comment by fariza** [comment]
Vale la pena seguir soportando python2? 
Las nuevas versiones de linux ya ni siquiera lo traen, y matplotlib,numpy,scipy estan ya planificando retirar el soporte de aqui a 3 annos.

**Comment by ramezquitao** [comment]
Yo diría que no. No es que tengamos un userbase gigante que requiera
mantener soporte de python 2.

**Comment by fariza** [comment]
Parece que todo esta funcionando en python3.5
Cierro por ahora, y si vemos mas errores se vuelve a abrir
