### ISSUE TITLE
Automatic version from TAG

### ISSUE THREAD

**Issue by ramezquitao** [cihologramas/pyoptools#164]
The build process uses the version information provided in the pyproject.toml file. If the value is not changed by hand in this file, the publication task will fail as it will try to upload an existing file to pypi. This information should not be hardwired, but should be read from the current git tag.

**Comment by semiversus** [comment]
I can help you with this issue. Will have a looked at it at the weekend.

**Comment by ramezquitao** [comment]
@semiversus Thanks, I just tested it and in is working fine.
