### ISSUE TITLE
metodo de instalacion

### ISSUE THREAD

**Issue by fariza** [cihologramas/pyoptools#27]
En este momento el paquete es instalable desde la linea de comandos con el `setup.py` y con la generacion de los `*deb`.
- Queremos mantener ambos metodos?
- No seria preferible simplificar el asunto y dejar uno solo?
- Si es instalable desde pypi, esto reemplaza la necesidad del `deb`?

Evidentemente mi preferencia limpiar y dejar solo el metodo de instalacion directamente por pypi para los releases estables, y desde el `setup.py` para instalar la version de desarrollo.

**Comment by ramezquitao** [comment]
A mi me gusta más montar el deb, para no tener por ahí archivos de instalaciones viejas volando. Yo preferiría mantenerlos ambos.

Pregunta: Yo nunca he creado instalables para pypi. ¿Es solo tener un setup.py bien escrito?

**Comment by fariza** [comment]
Para EMVA1288 yo segui http://peterdowns.com/posts/first-time-with-pypi.html
Es basicamente crear una cuenta y luego subir las cosas.
Lo chevere es que esta el testpypi para hacer pruebas y asegurarse que la instalacion funcione bien

**Comment by ramezquitao** [comment]
Ahh listo, es solo tener el setup.py. Para el deb es lo mismo, pues estamos
usando unos scripts (https://pypi.python.org/pypi/stdeb) que usan el
setup.py para crear el deb, o sea que si pypi funciona bien, el deb también
lo debe hacer.


Ricardo Amézquita Orozco
Doctor en Ciencias - Física
Director de Investigación y Desarrollo

CI Hologramas - Combustión Ingenieros S.A.S.
Cll 25B # 85B - 76, Bogotá / Colombia
Tel: 57-1-2635232
Fax: 57-1-4296516
http://www.cihologramas.com

**Comment by ijpulidos** [comment]
Se registró el proyecto en PIP, creo que es solo cuestión de tiempo para que aparezca con un `pip search pyoptools`. Se hicieron unos pequeños cambios para esto, https://github.com/cihologramas/pyoptools/commit/4471c3a14f102cb049429db0cc5531eb534321ba. Prácticamente se hizo un nuevo tag v0.1.1 y se cambiaron los archivos de setup correspondientes.

En PIP está acá: https://pypi.python.org/pypi?:action=display&name=pyoptools&version=0.1.1

Creo que se puede cerrar este issue ya.
