### ISSUE TITLE
zmf code

### ISSUE THREAD

**Issue by jordens** [cihologramas/pyoptools#40]
Pyoptools is a very nice tool! Thanks for developing it in the open.
You have copied GPL-licensed code into your BSD-licensed project:
https://github.com/cihologramas/pyoptools/blob/02e5180/pyoptools/raytrace/library/library.py#L233-L274
Could you please resolve the licensing issues that arise?

**Comment by ramezquitao** [comment]
Thanks for bringing up the issue. We will check it and solve it. Any way we are thinking to change pyoptools  license to a GPL-kind of license.

**Comment by jordens** [comment]
Cool! Looking forward to it. I also wouldn't mind being able to merge rayopt and pyoptools or sharing more code!

**Comment by ijpulidos** [comment]
Relicensing is now done in revisions d1a08580f62dbff1f3fdefca5d36c95481ca820c and 49f3aa146b3889704333af67984bf4fc6546edb0 , code has been updated to use GPLv3 license. Not sure what happens with previous forked/built BSD versions at this point.

**Comment by jordens** [comment]
Thanks!
FWIW, handling forks etc. is their (the forkers') responsibility.
