### ISSUE TITLE
polarization?

### ISSUE THREAD

**Issue by ZacDiggum** [cihologramas/pyoptools#47]
Hi there,

I'm planning to use pyoptools in an upcoming project involving diffractive elements.
I'd like to offload everything related to raytracing to pyoptools and implement the diffractive elements myself.  In order to do so, I need to propagate the rays' polarization states (linear only) from the source through a couple of refractive elements to the HOE. Naively spoken, I need pyoptools to carry the light to the HOE for me. :-)
Can pyoptools handle linear polarization? If so, is there anything in the documentation?

Thank you...

**Comment by ramezquitao** [comment]
Hi

At the moment pyoptools does not carry any polarization information, sorry.


Ricardo Amézquita Orozco
Doctor en Ciencias - Física
Director de Investigación y Desarrollo

CI Hologramas - Combustión Ingenieros S.A.S.
Cll 25B # 85B - 76, Bogotá / Colombia
Tel: 57-1-2635232
Fax: 57-1-4296516
http://www.cihologramas.com

**Comment by ZacDiggum** [comment]
Thank you for the info, @ramezquitao.
