### ISSUE TITLE
tests not working

### ISSUE THREAD

**Issue by ColinBrosseau** [cihologramas/pyoptools#63]
I wonder if tests are used for development. Right now, many tests don't pass. To make everything pass, I must modify such as

<pre><code>
diff --git a/pyoptools/tests/test_coding_standards.py b/pyoptools/tests/test_coding_standards.py
index 6fcdf9b..855e05a 100644
--- a/pyoptools/tests/test_coding_standards.py
+++ b/pyoptools/tests/test_coding_standards.py
@@ -68,6 +68,14 @@ EXCLUDE_FILES = ['zernike.py',
                  'definitions.pyx',
                  'plist.pyx',
                  'Poly2D.pyx',
+                 'idealcomponent.pyx',
+                 'powell_lens.py',
+                 'mirror.py',
+                 'diffraction.py',
+                 'cylindrical_lens.py',
+                 'powell.pyx',
+                 'zemax_import.py',
+                 'ipywidgets.py',
                  ]
</code></pre>

All these file where added after the introduction of tests. So, are existing tests ever used?

**Comment by ColinBrosseau** [comment]
Actually, to make test possible, one must add nose and pep8 to requirements.txt

**Comment by ColinBrosseau** [comment]
Solved by

https://github.com/cihologramas/pyoptools/pull/64

**Comment by ramezquitao** [comment]
Dear Colin

Thanks for your help. You are correct, some time ago we started to implement tests but this far from being complete or even working. If you have some suggestions they are welcome.

**Comment by ederag** [comment]
[pytest](https://docs.pytest.org) is a nice testing framework;
If there is an interest, it should be possible to do as in [geoptics](https://github.com/ederag/geoptics).

**Comment by ColinBrosseau** [comment]
Hi ramezquitao and ederag,

thanks for your answers. I'd like to contribute. Actually, I've began to write more tests for this project. Since nose is already here I added to that. But I personally prefer pytest. So if there is interest, I'd add pytest for pyoptools.
