### ISSUE TITLE
Maintenance of Python 2.7

### ISSUE THREAD

**Issue by ColinBrosseau** [cihologramas/pyoptools#67]
> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020.

Soon Python 2 will not be maintained anymore. Do we still need to drag this old guy any longer? Can we remove support to 2.7?

**Comment by ramezquitao** [comment]
Yes Colin, we should not care for python 2.7 compatibility. It was kept for
a little longer than recommended because FreeCAD didn't have support for
Python 3. But today there is no reason to keep it. At least not from our
side.

**Comment by ramezquitao** [comment]
Python 2.7 is deprecated. Closing issue
