### ISSUE TITLE
Lens focus wrong?

### ISSUE THREAD

**Issue by ldm78** [cihologramas/pyoptools#94]
I had some trouble with a lens, so I made a minimal notebook to confirm the focal length.
I attached it here:
[Toy.zip](https://github.com/cihologramas/pyoptools/files/6354454/Toy.zip)
Basically I'm sending three parallel rays through a lens with a focal length of 300mm, and they intersect at 437mm instead.
Am I doing something wrong, or is the surface of the lens too coarse for such a long focal length?

**Comment by ldm78** [comment]
It can't be the surface voxelation, the values don't change if I change the separation of the parallel rays or the radius of the lens.

**Comment by ramezquitao** [comment]
I will check tomorrow what is going on.

**Comment by ramezquitao** [comment]
I just checked your toy.zip file. There must be a numerical rounding issue with the spherical surfaces behaviour when the surface is very flat. I need to check what is going on. Still, if you use c2=0 (and not 1e-99), the SphericalLens constructor will use a flat surface instead an spherical one. In this case, the ray tracing seems to be working fine.
Can you check and give me feedback?

**Comment by ldm78** [comment]
Huh. I used that value because I got a division by zero error before.
I'll try it out.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by ederag** [comment]
@ldm78 Thanks for providing a fine minimal example !
With `c2 = 0`, `paraxial_constants` indeed fails with division by zero
(I have a fix, to submit after #116 is merged. With this fix, the notebook runs, and the focal length is correct).

`c2 = 1e-9`yields `3.00066643e+02`, close enough to the expected 300 mm,
but for
`c2 = 1e-10`, it jumps to the `4.37294252e+02`, which is close to the 437 mm observed for `c2 = 1e-99`.

**Comment by ramezquitao** [comment]
@ederag #116 is merged.

**Comment by ederag** [comment]
Thanks, #119 fixes the warning itself.
